[[project]]
    name = "Honeyfetch"
    desc = ""
    tags = [ "rust", "fetcher" ]
    link = [
        { name = "GitLab", url = "https://gitlab.com/ahoneybun/honeyfetch" }
    ]
    
[[project]]
    name = "Nyxi Installer"
    desc = "a fast installer for my personal NixOS setup."
    tags = [ "nixos", "installer" ]
    links = [
        { name = "GitLab", url = "https://gitlab.com/ahoneybun/nyxi-installer" }
    ]

[[project]]
    name = "My nix files for NixOS"
    desc = "including hosts like servers and homelab"
    tags = [ "nixos", "nixos-configs" ]
    links = [
        { name = "GitLab", url = "https://gitlab.com/ahoneybun/nix-configs" }
    ]

[[project]]
    name = "Random CAD files"
    desc = "things that I have made in FreeCAD"
    tags = [ "cad" ]
    links = [
        { name = "GitHub", url = "https://github.com/ahoneybun/Random-CAD/" }
    ]
